### PR TITLE
Add then to recognized keywords highlighting

### PR DESCRIPTION
**Pull request by windweaver828**
Added "then" near "if" for syntax highlighting

### CODE REVIEW

**Review by thmour — APPROVED** [review]

**Comment by thmour** [comment]
I thought this was dead with the new ES6 implementing all the features my language did for ES5

**Comment by windweaver828** [comment]
Sorry, what is ES5/6? Also I tried to add function in the same place but it broke the package in sublime, any idea why I cant add function the same way I did then?

**Comment by thmour** [comment]
I reverted the pull request as there is no then keyword in the miniscript language specification. You can google ES5 and ES6 and check http://thmour.github.io/miniscript/.

**Comment by windweaver828** [comment]
Sorry there must have been a glitch in my browser I swear I had it in 
there, do you want me to try again?

**Pull request merged**
